//! Golden test-vector corpus for the Hurray tensor interchange format.
//!
//! This crate defines a language-neutral set of byte-exact conformance vectors — encoded
//! tensor descriptors and a small HRRYFILE — together with a JSON manifest describing each
//! vector's expected decoded properties. The corpus is generated by the `generate-vectors`
//! binary and committed under `conformance/vectors/`. It is consumed by:
//!
//! - the Rust conformance test (`tests/verify.rs`), which decodes each committed vector and
//!   asserts it matches the manifest; and
//! - the Python binding's test suite, which loads the file vectors and checks the same
//!   manifest.
//!
//! One corpus, one source of truth: the reference bindings are validated against a shared
//! golden corpus (they are not independent re-implementations of the decoder).

use hurray_core::{
    buffer_size_bytes,
    layout::{CompositeLayout, CompositionRule, CsrLayout, MortonLayout, StridedLayout},
    BufferHandle, DeviceTag, ElementType, LayoutDescriptor, PerBlockAffine, QuantizationDescriptor,
    Shape, ShardDescriptor, SyncMode, TensorDescriptor, MIN_BUFFER_ALIGNMENT,
};
use serde::{Deserialize, Serialize};

/// Version of the format the corpus targets.
pub const FORMAT_VERSION: &str = "1.0";

/// Top-level manifest: the committed `manifest.json`.
#[derive(Debug, Serialize, Deserialize)]
pub struct Manifest {
    /// Hurray format version the corpus targets.
    pub format_version: String,
    /// Standalone encoded-descriptor vectors (Rust-verified).
    pub descriptors: Vec<DescriptorVector>,
    /// HRRYFILE vectors (verified by both the Rust and Python test suites).
    pub files: Vec<FileVector>,
}

/// One encoded-descriptor vector and its expected decoded properties.
#[derive(Debug, Serialize, Deserialize)]
pub struct DescriptorVector {
    /// Path of the `.bin` artifact, relative to `conformance/vectors/`.
    pub file: String,
    /// Human-readable description of what this vector exercises.
    pub description: String,
    /// The properties a conforming decoder MUST produce.
    pub expect: DescriptorExpect,
}

/// Expected decoded properties of a descriptor vector.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct DescriptorExpect {
    /// Descriptor `version_major`.
    pub version_major: u8,
    /// Descriptor `version_minor`.
    pub version_minor: u8,
    /// Element-type tag byte.
    pub element_type_tag: u8,
    /// Element-type language-agnostic name.
    pub element_type: String,
    /// Logical shape dimensions.
    pub shape: Vec<u64>,
    /// `byte_offset` field.
    pub byte_offset: u64,
    /// Layout tag byte.
    pub layout_tag: u8,
    /// Byte size of each buffer handle, in order.
    pub buffer_byte_sizes: Vec<u64>,
    /// Whether the `HAS_QUANTIZATION` section is present.
    pub has_quantization: bool,
    /// Whether the shard section is present.
    pub has_shard: bool,
}

/// One HRRYFILE vector and its expected contents.
#[derive(Debug, Serialize, Deserialize)]
pub struct FileVector {
    /// Path of the `.hrry` artifact, relative to `conformance/vectors/`.
    pub file: String,
    /// Human-readable description.
    pub description: String,
    /// Expected tensors, in index order.
    pub tensors: Vec<FileTensorExpect>,
    /// Expected key-value metadata.
    pub kv: Vec<KvExpect>,
}

/// Expected properties of one tensor in a file vector.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct FileTensorExpect {
    /// Tensor name in the file index.
    pub name: String,
    /// Element-type name.
    pub element_type: String,
    /// Element-type tag byte.
    pub element_type_tag: u8,
    /// Logical shape.
    pub shape: Vec<u64>,
    /// Total data-buffer bytes for this tensor.
    pub data_bytes: u64,
}

/// Expected key-value metadata entry (string- and int-valued entries only, for v1).
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct KvExpect {
    /// Key.
    pub key: String,
    /// Value kind: `"string"` or `"int64"`.
    pub kind: String,
    /// String value, when `kind == "string"`.
    pub value_string: Option<String>,
    /// Integer value, when `kind == "int64"`.
    pub value_int: Option<i64>,
}

/// The language-agnostic name of an element type, matching `docs/spec/element-types.md`.
pub fn element_type_name(t: ElementType) -> String {
    let s = match t {
        ElementType::Float16 => "float16",
        ElementType::BFloat16 => "bfloat16",
        ElementType::Float32 => "float32",
        ElementType::Float64 => "float64",
        ElementType::Int8 => "int8",
        ElementType::Uint8 => "uint8",
        ElementType::Int16 => "int16",
        ElementType::Uint16 => "uint16",
        ElementType::Int32 => "int32",
        ElementType::Uint32 => "uint32",
        ElementType::Int64 => "int64",
        ElementType::Uint64 => "uint64",
        ElementType::Bool => "bool",
        ElementType::Float8E4M3 => "float8_e4m3",
        ElementType::Float8E5M2 => "float8_e5m2",
        ElementType::Float8E8M0 => "float8_e8m0",
        ElementType::Float4E2M1 => "float4_e2m1",
        ElementType::Float6E2M3 => "float6_e2m3",
        ElementType::Float6E3M2 => "float6_e3m2",
        ElementType::Float128 => "float128",
        ElementType::Int4 => "int4",
        ElementType::Uint4 => "uint4",
        ElementType::Int2 => "int2",
        ElementType::Uint2 => "uint2",
        ElementType::Complex64 => "complex64",
        ElementType::Complex128 => "complex128",
        ElementType::Extension(_) => "extension",
    };
    s.to_string()
}

/// Derives the expected decoded properties from a descriptor (used to write the manifest).
pub fn derive_expect(desc: &TensorDescriptor) -> DescriptorExpect {
    DescriptorExpect {
        version_major: desc.version_major,
        version_minor: desc.version_minor,
        element_type_tag: desc.element_type.tag(),
        element_type: element_type_name(desc.element_type),
        shape: desc.shape.dims().to_vec(),
        byte_offset: desc.byte_offset,
        layout_tag: desc.layout.tag(),
        buffer_byte_sizes: desc.buffers.iter().map(|b| b.byte_size()).collect(),
        has_quantization: desc.quantization.is_some(),
        has_shard: desc.shard.is_some(),
    }
}

fn buf(byte_size: u64) -> BufferHandle {
    BufferHandle::new(
        byte_size,
        MIN_BUFFER_ALIGNMENT,
        DeviceTag::Cpu,
        SyncMode::ProducerSynced,
    )
    .expect("valid buffer handle")
}

/// A named descriptor vector: (file stem, description, descriptor).
pub struct NamedDescriptor {
    /// File stem (without extension), e.g. `row_major_f32`.
    pub stem: String,
    /// Human-readable description.
    pub description: String,
    /// The descriptor to encode.
    pub descriptor: TensorDescriptor,
}

fn dense(
    element_type: ElementType,
    dims: Vec<u64>,
    layout: LayoutDescriptor,
    num_elements: u64,
) -> TensorDescriptor {
    TensorDescriptor::new(
        1,
        0,
        element_type,
        Shape::new(dims).unwrap(),
        0,
        layout,
        vec![buf(buffer_size_bytes(element_type, num_elements))],
        None,
        None,
        None,
        None,
    )
    .expect("valid dense descriptor")
}

/// Builds the full set of standalone descriptor vectors.
pub fn descriptor_vectors() -> Vec<NamedDescriptor> {
    let mut v = Vec::new();

    let mut push = |stem: &str, description: &str, descriptor: TensorDescriptor| {
        v.push(NamedDescriptor {
            stem: stem.to_string(),
            description: description.to_string(),
            descriptor,
        });
    };

    // ── Dense, multiple element types ───────────────────────────────────────
    push(
        "row_major_f32_3x4",
        "Row-major float32 [3, 4]",
        dense(
            ElementType::Float32,
            vec![3, 4],
            LayoutDescriptor::RowMajor,
            12,
        ),
    );
    push(
        "row_major_int8_5",
        "Row-major int8 [5]",
        dense(ElementType::Int8, vec![5], LayoutDescriptor::RowMajor, 5),
    );
    push(
        "row_major_f16_2x2",
        "Row-major float16 [2, 2]",
        dense(
            ElementType::Float16,
            vec![2, 2],
            LayoutDescriptor::RowMajor,
            4,
        ),
    );
    push(
        "bool_packed_10",
        "Row-major bool [10] (packed 8 per byte → 2 bytes)",
        dense(ElementType::Bool, vec![10], LayoutDescriptor::RowMajor, 10),
    );

    // ── Strided ─────────────────────────────────────────────────────────────
    push(
        "strided_f32_3x4",
        "Strided float32 [3, 4] with row-major strides [4, 1]",
        dense(
            ElementType::Float32,
            vec![3, 4],
            LayoutDescriptor::Strided(StridedLayout::new(vec![4, 1])),
            12,
        ),
    );

    // ── Morton ──────────────────────────────────────────────────────────────
    push(
        "morton_f32_4x4",
        "Morton (Z-order) float32 [4, 4], morton_bits [2, 2]",
        dense(
            ElementType::Float32,
            vec![4, 4],
            LayoutDescriptor::Morton(MortonLayout::new(vec![2, 2]).unwrap()),
            16,
        ),
    );

    // ── Empty tensor ────────────────────────────────────────────────────────
    push(
        "empty_f32_0x4",
        "Empty row-major float32 [0, 4] (zero elements)",
        dense(
            ElementType::Float32,
            vec![0, 4],
            LayoutDescriptor::RowMajor,
            0,
        ),
    );

    // ── Sharded ─────────────────────────────────────────────────────────────
    {
        let d = TensorDescriptor::new(
            1,
            0,
            ElementType::Float32,
            Shape::new(vec![8, 4]).unwrap(),
            0,
            LayoutDescriptor::RowMajor,
            vec![buf(buffer_size_bytes(ElementType::Float32, 32))],
            None,
            Some(ShardDescriptor::new(vec![8, 8], vec![0, 4]).unwrap()),
            None,
            None,
        )
        .expect("valid sharded descriptor");
        push(
            "sharded_f32_8x4",
            "Row-major float32 [8, 4] shard at column offset 4 of an [8, 8] parent",
            d,
        );
    }

    // ── CSR (sparse, multi-buffer) ──────────────────────────────────────────
    {
        // 3×3 matrix, nnz = 2: values(f32), col_indices(u64), row_ptr(u64, nrows+1).
        let nnz = 2u64;
        let nrows = 3u64;
        let d = TensorDescriptor::new(
            1,
            0,
            ElementType::Float32,
            Shape::new(vec![3, 3]).unwrap(),
            0,
            LayoutDescriptor::Csr(CsrLayout::new(nnz)),
            vec![
                buf(buffer_size_bytes(ElementType::Float32, nnz)),
                buf(buffer_size_bytes(ElementType::Uint64, nnz)),
                buf(buffer_size_bytes(ElementType::Uint64, nrows + 1)),
            ],
            None,
            None,
            None,
            None,
        )
        .expect("valid CSR descriptor");
        push("csr_f32_3x3", "CSR float32 [3, 3], nnz = 2", d);
    }

    // ── Composite head (virtual, no data) ───────────────────────────────────
    {
        let d = TensorDescriptor::new(
            1,
            0,
            ElementType::Float32,
            Shape::new(vec![8, 8]).unwrap(),
            0,
            LayoutDescriptor::Composite(
                CompositeLayout::new(CompositionRule::Partition, 2).unwrap(),
            ),
            vec![],
            None,
            None,
            None,
            None,
        )
        .expect("valid composite head");
        push(
            "composite_head_partition",
            "Composite partition head [8, 8], member_count = 2 (owns no data)",
            d,
        );
    }

    // ── Quantized (per-block affine, int4) ──────────────────────────────────
    {
        // int4 [128, 128], per-block-affine, block_size 128 → one block per row axis.
        let pba = PerBlockAffine::new_symmetric(1, 128, 1, ElementType::Float16).unwrap();
        let num_blocks = pba.num_blocks_per_axis(128) * 128;
        let quant = QuantizationDescriptor::PerBlockAffine(pba);
        let d = TensorDescriptor::new(
            1,
            0,
            ElementType::Int4,
            Shape::new(vec![128, 128]).unwrap(),
            0,
            LayoutDescriptor::RowMajor,
            vec![
                buf(buffer_size_bytes(ElementType::Int4, 128 * 128)),
                buf(buffer_size_bytes(ElementType::Float16, num_blocks)),
            ],
            Some(quant.encode_to_vec()),
            None,
            None,
            None,
        )
        .expect("valid quantized descriptor");
        push(
            "quant_per_block_int4_128x128",
            "int4 [128, 128] per-block-affine (float16 scales)",
            d,
        );
    }

    v
}
