/* Hurray C ABI — https://github.com/pgillet/hurray */

#ifndef HURRAY_H
#define HURRAY_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// The integer version of the Hurray C ABI exposed by this build.
//
// Callers SHOULD retrieve this at runtime via [`hurray_c_abi_version`] and
// compare it to the version they were compiled against.
//
// # Examples
//
// ```
// use hurray_ffi::HURRAY_C_ABI_VERSION;
//
// assert_eq!(HURRAY_C_ABI_VERSION, 4);
// ```
#define HURRAY_C_ABI_VERSION 4

// Opaque handle to a buffer registered with the Hurray C ABI.
//
// This struct is **not** `#[repr(C)]`; its internal layout is an
// implementation detail. Callers MUST treat it as a black-box opaque
// pointer. The handle is heap-allocated by [`hurray_buffer_from_ptr`] and
// MUST be released exactly once by [`hurray_buffer_destroy`].
typedef struct HurrayBuffer HurrayBuffer;

// Opaque handle to an ordered, owning list of [`HurrayBuffer`] handles.
//
// Like [`HurrayBuffer`], this struct is **not** `#[repr(C)]`; its layout is an
// implementation detail and callers MUST treat it as a black-box pointer.
// Keeping it opaque is what allows [`hurray_buffer_list_get`] to bounds-check
// and to hand back a borrowed handle — a bare `HurrayBuffer**` array could do
// neither.
typedef struct HurrayBufferList HurrayBufferList;

// Opaque handle to a decoded tensor descriptor.
//
// This struct is **not** `#[repr(C)]`; its layout is an implementation
// detail. Callers MUST treat it as a black-box opaque pointer created by
// [`hurray_descriptor_decode`] and destroyed by [`hurray_descriptor_destroy`].
typedef struct HurrayDescriptor HurrayDescriptor;

// Opaque handle to an async streaming reader (full implementation deferred).
//
// A reader bridges `hurray-io`'s async streaming layer into the C ABI.
// The async-to-sync bridging strategy (e.g., blocking executor, channel
// hand-off) is deferred; this stub allows cbindgen to emit the type
// declaration in the generated header.
typedef struct HurrayReader HurrayReader;

// Opaque handle to a capsule's tensor context: descriptor bytes, ABI version,
// and an owner reference.
//
// Like every other handle in this ABI, this struct is **not** `#[repr(C)]`; its
// layout is an implementation detail and callers MUST treat it as a black-box
// pointer. Publishing the layout would buy nothing — a caller holding a capsule
// already links this library to read its buffer list — and would freeze the
// layout for the life of the major version (ADR-034 § 2).
typedef struct HurrayTensorContext HurrayTensorContext;

// Opaque handle to an async streaming writer (full implementation deferred).
//
// Symmetric to [`HurrayReader`]. Deferred pending the async bridge design.
typedef struct HurrayWriter HurrayWriter;

// Integer status code returned by every Hurray C ABI function.
//
// Zero (`HURRAY_OK`) indicates success. All negative values indicate errors.
// Positive values are reserved for future use.
//
// # Examples
//
// ```
// use hurray_ffi::{HurrayStatus, HURRAY_OK};
//
// fn check(s: HurrayStatus) {
//     assert_eq!(s, HURRAY_OK);
// }
// check(HURRAY_OK);
// ```
typedef int32_t HurrayStatus;

// Optional release callback invoked by [`hurray_buffer_destroy`].
//
// The first argument is the `data` pointer passed to [`hurray_buffer_from_ptr`].
// The second argument is the `release_context` pointer passed to the same
// function. Both arguments carry the exact values provided at construction time.
//
// Implementations MUST NOT call back into the Hurray C ABI from within this
// callback; doing so may cause deadlocks or use-after-free.
typedef void (*HurrayReleaseCallback)(void*, void*);

// Payload for the `ConsumerStream` sync mode handoff.
//
// The consumer supplies this struct when calling
// [`hurray_buffer_handoff_consumer_stream`] to declare the stream on which
// they intend to use the buffer.
typedef struct HurraySyncConsumerStreamPayload {
    // Non-null consumer stream handle (e.g., `cudaStream_t`).
    void *consumer_stream;
    // Wire byte of the device that owns `consumer_stream`.
    uint8_t consumer_stream_device_tag;
} HurraySyncConsumerStreamPayload;

// Optional callback invoked to release a sync event handle.
//
// The first argument is the event handle; the second is the
// `event_release_context` pointer. MUST NOT call back into the Hurray C ABI.
typedef void (*HurrayEventReleaseFn)(void*, void*);

// Payload for the `Event` sync mode handoff.
//
// The consumer supplies this struct when calling
// [`hurray_buffer_handoff_event`] to provide the device event that the
// producer recorded and on which the consumer will wait.
typedef struct HurraySyncEventPayload {
    // Non-null device-event handle (e.g., `cudaEvent_t`).
    void *sync_handle;
    // Wire byte of the device on which `sync_handle` was recorded.
    uint8_t sync_handle_device_tag;
    // Release callback for `sync_handle`; MUST be non-null.
    HurrayEventReleaseFn event_release_fn;
    // Opaque context forwarded to `event_release_fn`; MAY be null.
    void *event_release_context;
} HurraySyncEventPayload;

// Callback invoked exactly once by [`hurray_tensor_context_destroy`] to release
// whatever keeps the tensor's memory alive.
//
// The argument is the `owner` pointer passed to [`hurray_tensor_context_new`],
// with the exact value provided at construction time.
//
// Implementations MUST NOT call back into the Hurray C ABI from within this
// callback; doing so may cause deadlocks or use-after-free.
typedef void (*HurrayOwnerReleaseFn)(void*);

// Operation completed successfully.
#define HURRAY_OK 0

// The descriptor magic bytes were not `"HRRY"` (`0x48 0x52 0x52 0x59`).
#define HURRAY_ERR_INVALID_MAGIC -1

// The descriptor version is not supported by this implementation.
#define HURRAY_ERR_VERSION_MISMATCH -2

// A layout descriptor field or tag is invalid.
#define HURRAY_ERR_INVALID_LAYOUT -3

// A type tag, device tag, or memory class is invalid.
#define HURRAY_ERR_INVALID_TYPE -4

// An output buffer is too small to hold the result.
#define HURRAY_ERR_BUFFER_TOO_SMALL -5

// A required pointer argument is null.
#define HURRAY_ERR_NULL_POINTER -6

// The function panicked internally; the handle MUST NOT be reused.
#define HURRAY_ERR_INTERNAL_PANIC -7

// The sync mode byte is not a recognized value.
#define HURRAY_ERR_INVALID_SYNC_MODE -8

// A sync-mode handoff payload does not match the buffer's declared sync mode.
#define HURRAY_ERR_SYNC_MODE_MISMATCH -9

// An unclassified internal error occurred.
#define HURRAY_ERR_INTERNAL -10

// An index argument is outside the valid range for the collection.
#define HURRAY_ERR_INDEX_OUT_OF_BOUNDS -11

// Reads the declared alignment of a buffer handle (in bytes).
//
// # Safety
//
// `buffer` and `out_alignment` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_alignment(const struct HurrayBuffer *buffer, uint32_t *out_alignment) ;

// Reads the byte size of a buffer handle.
//
// # Safety
//
// `buffer` and `out_byte_size` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_byte_size(const struct HurrayBuffer *buffer, uint64_t *out_byte_size) ;

// Reads the raw data pointer stored in a buffer handle.
//
// # Safety
//
// `buffer` and `out_data` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_data_ptr(const struct HurrayBuffer *buffer, void **out_data) ;

// Destroys a [`HurrayBuffer`] handle and invokes the release callback.
//
// After this call, `buffer` is no longer valid and MUST NOT be dereferenced.
// In debug builds, a double-free attempt returns [`HURRAY_ERR_INTERNAL`].
//
// # Safety
//
// - `buffer` MUST have been created by [`hurray_buffer_from_ptr`].
// - `buffer` MUST NOT have been previously destroyed.
 HurrayStatus hurray_buffer_destroy(struct HurrayBuffer *buffer) ;

// Reads the device tag wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_device_tag` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_device_tag(const struct HurrayBuffer *buffer, uint8_t *out_device_tag) ;

// Creates a new [`HurrayBuffer`] handle from a raw data pointer and metadata.
//
// The caller retains ownership of `data` until the handle is destroyed via
// [`hurray_buffer_destroy`], at which point the `release` callback (if
// non-null) is invoked with `(data, release_context)`. If `release` is null,
// the caller is responsible for freeing `data` after destroying the handle.
//
// # Arguments
//
// - `data` — Non-null pointer to the first byte of the buffer. MUST be
//   aligned to at least `alignment` bytes.
// - `byte_size` — Length of the buffer in bytes.
// - `alignment` — Declared alignment of `data` in bytes; MUST be a power of
//   two and at least [`hurray_core::MIN_BUFFER_ALIGNMENT`] for non-empty
//   buffers.
// - `device_tag` — Wire byte identifying the memory space (see
//   `docs/spec/buffer-protocol.md § Device Tags`).
// - `sync_mode` — Wire byte for producer/consumer ordering (see
//   `docs/spec/buffer-protocol.md § Synchronization Mode`).
// - `memory_class` — Wire byte for memory accessibility class.
// - `release` — Optional callback invoked on [`hurray_buffer_destroy`].
// - `release_context` — Opaque context pointer forwarded to `release`; MAY
//   be null.
// - `out_handle` — Non-null pointer to a `*mut HurrayBuffer`; set to the
//   newly allocated handle on success.
//
// # Safety
//
// - `data` MUST be a valid, non-null pointer to at least `byte_size` bytes.
// - `data` MUST remain valid until the release callback is called.
// - `out_handle` MUST be a valid, non-null, writable pointer.
// - `release_context` lifetime is caller-managed; it MUST remain valid until
//   the release callback returns.

HurrayStatus hurray_buffer_from_ptr(void *data,
                                    uint64_t byte_size,
                                    uint32_t alignment,
                                    uint8_t device_tag,
                                    uint8_t sync_mode,
                                    uint8_t memory_class,
                                    HurrayReleaseCallback release,
                                    void *release_context,
                                    struct HurrayBuffer **out_handle)
;

// Validates a `ConsumerStream`-mode sync handoff from producer to consumer.
//
// Checks that:
// - The buffer's declared sync mode is [`SyncMode::ConsumerStream`].
// - `payload.consumer_stream` is non-null.
// - `payload.consumer_stream_device_tag` matches the buffer's declared device
//   tag.
//
// Returns [`HURRAY_OK`] if all checks pass; [`HURRAY_ERR_SYNC_MODE_MISMATCH`]
// otherwise.
//
// # Safety
//
// `buffer` and `payload` MUST be valid, non-null pointers pointing to live
// objects.

HurrayStatus hurray_buffer_handoff_consumer_stream(const struct HurrayBuffer *buffer,
                                                   const struct HurraySyncConsumerStreamPayload *payload)
;

// Validates an `Event`-mode sync handoff from producer to consumer.
//
// Checks that:
// - The buffer's declared sync mode is [`SyncMode::Event`].
// - `payload.sync_handle` is non-null.
// - `payload.event_release_fn` is non-null.
// - `payload.sync_handle_device_tag` matches the buffer's declared device tag.
//
// Returns [`HURRAY_OK`] if all checks pass; [`HURRAY_ERR_SYNC_MODE_MISMATCH`]
// otherwise.
//
// # Safety
//
// `buffer` and `payload` MUST be valid, non-null pointers pointing to live
// objects.

HurrayStatus hurray_buffer_handoff_event(const struct HurrayBuffer *buffer,
                                         const struct HurraySyncEventPayload *payload)
;

// Validates a `ProducerSynced`-mode sync handoff.
//
// Checks that the buffer's declared sync mode is
// [`SyncMode::ProducerSynced`]. This mode requires no payload — calling
// this function is itself the assertion that the producer has already issued
// a host-side wait.
//
// Returns [`HURRAY_OK`] if the buffer is `ProducerSynced`;
// [`HURRAY_ERR_SYNC_MODE_MISMATCH`] otherwise.
//
// # Safety
//
// `buffer` MUST be a valid, non-null pointer to a live [`HurrayBuffer`].
 HurrayStatus hurray_buffer_handoff_producer_synced(const struct HurrayBuffer *buffer) ;

// Destroys `*list` and every [`HurrayBuffer`] it owns, then writes null through
// `list`.
//
// Nulling the caller's pointer is the sound half of Arrow's "release marks the
// structure released" discipline: the list allocation itself is freed here, so
// a marker written inside it could not be read back, but the caller's own
// variable can be invalidated.
//
// Each owned slot is nulled as its handle is destroyed, so a release callback
// that panics or re-enters cannot cause a double free. A panicking callback
// leaks the remainder of the list rather than corrupting it.
//
// Passing a pointer to a null pointer is a no-op and returns [`HURRAY_OK`],
// which makes cleanup paths idempotent.
//
// # Safety
//
// - `list` MUST be a valid, non-null, writable pointer to a `*mut HurrayBufferList`.
// - `*list` MUST be a live handle from [`hurray_buffer_list_new`], or null.
//
// # Examples
//
// ```
// use hurray_ffi::buffer_list::{hurray_buffer_list_destroy, hurray_buffer_list_new};
// use hurray_ffi::{HurrayBufferList, HURRAY_OK};
//
// let mut list: *mut HurrayBufferList = std::ptr::null_mut();
// unsafe { hurray_buffer_list_new(0, &mut list) };
//
// assert_eq!(unsafe { hurray_buffer_list_destroy(&mut list) }, HURRAY_OK);
// assert!(list.is_null());
//
// // Idempotent: destroying an already-nulled pointer is a no-op.
// assert_eq!(unsafe { hurray_buffer_list_destroy(&mut list) }, HURRAY_OK);
// ```
 HurrayStatus hurray_buffer_list_destroy(struct HurrayBufferList **list) ;

// Borrows the [`HurrayBuffer`] at `index`.
//
// The returned handle is **borrowed**: ownership stays with the list, and the
// caller MUST NOT call `hurray_buffer_destroy` on it. It stays valid until the
// list is destroyed.
//
// Returns [`HURRAY_ERR_INDEX_OUT_OF_BOUNDS`] if `index` is not less than the
// list length.
//
// # Safety
//
// - `list` MUST be a live handle from [`hurray_buffer_list_new`].
// - `out_buffer` MUST be a valid, non-null, writable pointer.
//
// # Examples
//
// ```
// use hurray_ffi::buffer_list::{
//     hurray_buffer_list_destroy, hurray_buffer_list_get, hurray_buffer_list_new,
// };
// use hurray_ffi::status::HURRAY_ERR_INDEX_OUT_OF_BOUNDS;
// use hurray_ffi::{HurrayBuffer, HurrayBufferList};
//
// let mut list: *mut HurrayBufferList = std::ptr::null_mut();
// unsafe { hurray_buffer_list_new(0, &mut list) };
//
// // An empty list has no index 0.
// let mut got: *mut HurrayBuffer = std::ptr::null_mut();
// assert_eq!(
//     unsafe { hurray_buffer_list_get(list, 0, &mut got) },
//     HURRAY_ERR_INDEX_OUT_OF_BOUNDS
// );
//
// unsafe { hurray_buffer_list_destroy(&mut list) };
// ```

HurrayStatus hurray_buffer_list_get(const struct HurrayBufferList *list,
                                    uint64_t index,
                                    struct HurrayBuffer **out_buffer)
;

// Reads the number of buffers in `list`.
//
// # Safety
//
// - `list` MUST be a live handle from [`hurray_buffer_list_new`].
// - `out_len` MUST be a valid, non-null, writable pointer.
//
// # Examples
//
// ```
// use hurray_ffi::buffer_list::{
//     hurray_buffer_list_destroy, hurray_buffer_list_len, hurray_buffer_list_new,
// };
// use hurray_ffi::{HurrayBufferList, HURRAY_OK};
//
// let mut list: *mut HurrayBufferList = std::ptr::null_mut();
// unsafe { hurray_buffer_list_new(0, &mut list) };
//
// let mut len: u64 = 7;
// assert_eq!(unsafe { hurray_buffer_list_len(list, &mut len) }, HURRAY_OK);
// assert_eq!(len, 0);
//
// unsafe { hurray_buffer_list_destroy(&mut list) };
// ```
 HurrayStatus hurray_buffer_list_len(const struct HurrayBufferList *list, uint64_t *out_len) ;

// Creates an empty [`HurrayBufferList`].
//
// `capacity` is a hint only; the list grows as needed. Pass the tensor's
// buffer count to avoid reallocation.
//
// The caller owns the returned list and MUST destroy it exactly once with
// [`hurray_buffer_list_destroy`].
//
// # Safety
//
// `out_list` MUST be a valid, non-null, writable pointer.
//
// # Examples
//
// ```
// use hurray_ffi::buffer_list::{hurray_buffer_list_destroy, hurray_buffer_list_new};
// use hurray_ffi::{HurrayBufferList, HURRAY_OK};
//
// let mut list: *mut HurrayBufferList = std::ptr::null_mut();
// assert_eq!(unsafe { hurray_buffer_list_new(2, &mut list) }, HURRAY_OK);
// assert!(!list.is_null());
//
// assert_eq!(unsafe { hurray_buffer_list_destroy(&mut list) }, HURRAY_OK);
// assert!(list.is_null()); // destroy nulls the caller's pointer
// ```
 HurrayStatus hurray_buffer_list_new(uint64_t capacity, struct HurrayBufferList **out_list) ;

// Appends `buffer` to `list`, transferring ownership of the handle to the list.
//
// On success the caller MUST NOT destroy `buffer` — destroying the list
// destroys it. On failure ownership stays with the caller.
//
// Buffers MUST be pushed in descriptor buffer-table order: the first push is
// buffer index `0`, the second is index `1`, and so on.
//
// # Safety
//
// - `list` MUST be a live handle from [`hurray_buffer_list_new`].
// - `buffer` MUST be a live handle from `hurray_buffer_from_ptr` that has not
//   been destroyed and is not already owned by another list.
//
// # Examples
//
// ```
// use hurray_ffi::buffer::hurray_buffer_from_ptr;
// use hurray_ffi::buffer_list::{
//     hurray_buffer_list_destroy, hurray_buffer_list_len, hurray_buffer_list_new,
//     hurray_buffer_list_push,
// };
// use hurray_ffi::{HurrayBuffer, HurrayBufferList, HURRAY_OK};
//
// #[repr(align(64))]
// struct Aligned([u8; 64]);
// let mut data = Aligned([0u8; 64]);
//
// let mut buffer: *mut HurrayBuffer = std::ptr::null_mut();
// assert_eq!(
//     unsafe {
//         hurray_buffer_from_ptr(
//             data.0.as_mut_ptr().cast(), 64, 64, 0, 0, 0,
//             None, std::ptr::null_mut(), &mut buffer,
//         )
//     },
//     HURRAY_OK
// );
//
// let mut list: *mut HurrayBufferList = std::ptr::null_mut();
// unsafe { hurray_buffer_list_new(1, &mut list) };
// assert_eq!(unsafe { hurray_buffer_list_push(list, buffer) }, HURRAY_OK);
//
// let mut len: u64 = 0;
// unsafe { hurray_buffer_list_len(list, &mut len) };
// assert_eq!(len, 1);
//
// // Destroying the list destroys the pushed buffer too.
// unsafe { hurray_buffer_list_destroy(&mut list) };
// ```
 HurrayStatus hurray_buffer_list_push(struct HurrayBufferList *list, struct HurrayBuffer *buffer) ;

// Reads the memory class wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_memory_class` MUST be valid, non-null pointers.

HurrayStatus hurray_buffer_memory_class(const struct HurrayBuffer *buffer,
                                        uint8_t *out_memory_class)
;

// Reads the sync mode wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_sync_mode` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_sync_mode(const struct HurrayBuffer *buffer, uint8_t *out_sync_mode) ;

// Returns the [`HURRAY_C_ABI_VERSION`] constant.
//
// This function is infallible and requires no panic barrier.
//
// # Examples
//
// ```
// assert_eq!(unsafe { hurray_ffi::hurray_c_abi_version() }, 4);
// ```
 uint32_t hurray_c_abi_version(void) ;

// Reads the number of buffer handles in the tensor descriptor's buffer table.
//
// # Safety
//
// `handle` and `out_count` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_buffer_count(const struct HurrayDescriptor *handle,
                                            uint32_t *out_count)
;

// Reads the byte offset from the start of buffer 0 to logical element `[0,…,0]`.
//
// # Safety
//
// `handle` and `out_offset` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_byte_offset(const struct HurrayDescriptor *handle,
                                           uint64_t *out_offset)
;

// Decodes a binary tensor descriptor from a byte buffer.
//
// On success, `*out_handle` is set to a newly allocated [`HurrayDescriptor`]
// that MUST be released via [`hurray_descriptor_destroy`].
//
// # Arguments
//
// - `bytes` — Non-null pointer to the first byte of the encoded descriptor.
// - `len` — Number of bytes readable at `bytes`.
// - `out_handle` — Non-null pointer to a `*mut HurrayDescriptor`; set on
//   success.
//
// # Safety
//
// - `bytes` MUST be valid and readable for `len` bytes for the duration of
//   this call.
// - `out_handle` MUST be a valid, non-null, writable pointer.

HurrayStatus hurray_descriptor_decode(const uint8_t *bytes,
                                      uintptr_t len,
                                      struct HurrayDescriptor **out_handle)
;

// Destroys a [`HurrayDescriptor`] handle and frees its memory.
//
// After this call, `handle` is no longer valid and MUST NOT be dereferenced.
//
// # Safety
//
// - `handle` MUST have been created by [`hurray_descriptor_decode`].
// - `handle` MUST NOT have been previously destroyed.
 HurrayStatus hurray_descriptor_destroy(struct HurrayDescriptor *handle) ;

// Reads the element type tag byte of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_tag` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_element_type_tag(const struct HurrayDescriptor *handle,
                                                uint8_t *out_tag)
;

// Reads the layout tag byte of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_tag` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_layout_tag(const struct HurrayDescriptor *handle,
                                          uint8_t *out_tag)
;

// Reads the rank (number of dimensions) of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_rank` MUST be valid, non-null pointers.
 HurrayStatus hurray_descriptor_rank(const struct HurrayDescriptor *handle, uint32_t *out_rank) ;

// Reads the shape (dimension sizes) of a tensor descriptor.
//
// This function uses a **capacity/length in-out pattern**:
//
// 1. Set `*out_rank` to the capacity of the `out_dims` array (number of
//    `uint64_t` elements it can hold), or to `0` if `out_dims` is null.
// 2. On return, `*out_rank` always contains the true rank of the tensor.
// 3. If `out_dims` is null OR the capacity was less than the true rank,
//    the function returns [`HURRAY_ERR_BUFFER_TOO_SMALL`] and `*out_rank`
//    contains the true rank so the caller can allocate and retry.
// 4. Otherwise the function writes the dimension sizes into `out_dims[0..rank]`
//    and returns [`HURRAY_OK`].
//
// # Safety
//
// - `handle` and `out_rank` MUST be valid, non-null pointers.
// - If `out_dims` is non-null it MUST be writable for `capacity` × 8 bytes,
//   where `capacity` is the value at `*out_rank` on entry.

HurrayStatus hurray_descriptor_shape(const struct HurrayDescriptor *handle,
                                     uint64_t *out_dims,
                                     uintptr_t *out_rank)
;

// Reads the ABI version recorded by the producing build.
//
// **Call this first.** It is the one accessor guaranteed to work on a context
// produced by any version of this ABI; every other accessor assumes a caller
// that has already compared this value against its own
// [`HURRAY_C_ABI_VERSION`](crate::HURRAY_C_ABI_VERSION) and found it
// compatible (ADR-034 § 4). That ordering is what lets later versions add
// accessors without breaking older consumers.
//
// # Safety
//
// `ctx` MUST be a live handle from [`hurray_tensor_context_new`], and `out`
// MUST be a valid, writable pointer.
//
// # Examples
//
// ```
// use hurray_ffi::tensor_context::{
//     hurray_tensor_context_abi_version, hurray_tensor_context_destroy,
//     hurray_tensor_context_new,
// };
// use hurray_ffi::{HurrayTensorContext, HURRAY_C_ABI_VERSION, HURRAY_OK};
//
// let mut ctx: *mut HurrayTensorContext = std::ptr::null_mut();
// unsafe {
//     hurray_tensor_context_new(
//         HURRAY_C_ABI_VERSION, std::ptr::null(), 0, std::ptr::null_mut(), None, &mut ctx,
//     );
// }
//
// let mut version: u32 = 0;
// assert_eq!(
//     unsafe { hurray_tensor_context_abi_version(ctx, &mut version) },
//     HURRAY_OK,
// );
// assert_eq!(version, HURRAY_C_ABI_VERSION);
//
// unsafe { hurray_tensor_context_destroy(&mut ctx) };
// ```

HurrayStatus hurray_tensor_context_abi_version(const struct HurrayTensorContext *ctx,
                                               uint32_t *out)
;

// Borrows the encoded tensor descriptor.
//
// The returned pointer is owned by `ctx` and is valid until the context is
// destroyed; the caller MUST NOT free it. Decode it with
// [`hurray_descriptor_decode`](crate::descriptor::hurray_descriptor_decode) to
// read the element type, shape, layout, and optional sections.
//
// `out_len` is `0` — and `out_bytes` null — for a context created without a
// descriptor.
//
// # Safety
//
// `ctx` MUST be a live handle from [`hurray_tensor_context_new`], and both out
// pointers MUST be valid and writable.
//
// # Examples
//
// ```
// use hurray_ffi::tensor_context::{
//     hurray_tensor_context_descriptor, hurray_tensor_context_destroy,
//     hurray_tensor_context_new,
// };
// use hurray_ffi::{HurrayTensorContext, HURRAY_C_ABI_VERSION, HURRAY_OK};
//
// let descriptor = [0x48u8, 0x52, 0x52, 0x59];
// let mut ctx: *mut HurrayTensorContext = std::ptr::null_mut();
// unsafe {
//     hurray_tensor_context_new(
//         HURRAY_C_ABI_VERSION,
//         descriptor.as_ptr(),
//         descriptor.len() as u64,
//         std::ptr::null_mut(),
//         None,
//         &mut ctx,
//     );
// }
//
// let mut bytes: *const u8 = std::ptr::null();
// let mut len: u64 = 0;
// assert_eq!(
//     unsafe { hurray_tensor_context_descriptor(ctx, &mut bytes, &mut len) },
//     HURRAY_OK,
// );
// assert_eq!(len, 4);
// assert_eq!(unsafe { std::slice::from_raw_parts(bytes, len as usize) }, &descriptor);
//
// unsafe { hurray_tensor_context_destroy(&mut ctx) };
// ```

HurrayStatus hurray_tensor_context_descriptor(const struct HurrayTensorContext *ctx,
                                              const uint8_t **out_bytes,
                                              uint64_t *out_len)
;

// Destroys a [`HurrayTensorContext`], invoking its owner-release callback, and
// nulls the caller's pointer.
//
// Destroying a null handle is a no-op that returns [`HURRAY_OK`], so the call
// is safe to make unconditionally on a cleanup path.
//
// # Safety
//
// - `ctx` MUST be a valid, writable pointer to a handle slot.
// - The handle it points to MUST come from [`hurray_tensor_context_new`] and
//   MUST NOT have been destroyed already.
//
// # Examples
//
// ```
// use hurray_ffi::tensor_context::{hurray_tensor_context_destroy, hurray_tensor_context_new};
// use hurray_ffi::{HurrayTensorContext, HURRAY_C_ABI_VERSION, HURRAY_OK};
//
// let mut ctx: *mut HurrayTensorContext = std::ptr::null_mut();
// unsafe {
//     hurray_tensor_context_new(
//         HURRAY_C_ABI_VERSION, std::ptr::null(), 0, std::ptr::null_mut(), None, &mut ctx,
//     );
// }
//
// assert_eq!(unsafe { hurray_tensor_context_destroy(&mut ctx) }, HURRAY_OK);
// assert!(ctx.is_null());
// // Destroying again is a no-op, not a double free.
// assert_eq!(unsafe { hurray_tensor_context_destroy(&mut ctx) }, HURRAY_OK);
// ```
 HurrayStatus hurray_tensor_context_destroy(struct HurrayTensorContext **ctx) ;

// Creates a [`HurrayTensorContext`] owning a copy of `descriptor_bytes`.
//
// `abi_version` MUST be the producing build's `HURRAY_C_ABI_VERSION`; a consumer
// compares it against its own before trusting anything else about the capsule.
//
// `owner` and `owner_release` are optional and opaque. When `owner_release` is
// non-null it is invoked exactly once, with `owner`, during
// [`hurray_tensor_context_destroy`].
//
// The caller owns the returned handle and MUST destroy it exactly once.
//
// # Safety
//
// - `out_ctx` MUST be a valid, non-null, writable pointer.
// - `descriptor_bytes` MUST point to at least `descriptor_len` readable bytes,
//   unless `descriptor_len` is `0`, in which case it MAY be null.
// - `owner` MUST remain valid until `owner_release` is invoked.
//
// # Examples
//
// ```
// use hurray_ffi::tensor_context::{
//     hurray_tensor_context_destroy, hurray_tensor_context_new,
// };
// use hurray_ffi::{HurrayTensorContext, HURRAY_C_ABI_VERSION, HURRAY_OK};
//
// let descriptor = [0x48u8, 0x52, 0x52, 0x59]; // "HRRY"
// let mut ctx: *mut HurrayTensorContext = std::ptr::null_mut();
// assert_eq!(
//     unsafe {
//         hurray_tensor_context_new(
//             HURRAY_C_ABI_VERSION,
//             descriptor.as_ptr(),
//             descriptor.len() as u64,
//             std::ptr::null_mut(),
//             None,
//             &mut ctx,
//         )
//     },
//     HURRAY_OK,
// );
//
// assert_eq!(unsafe { hurray_tensor_context_destroy(&mut ctx) }, HURRAY_OK);
// assert!(ctx.is_null()); // destroy nulls the caller's pointer
// ```

HurrayStatus hurray_tensor_context_new(uint32_t abi_version,
                                       const uint8_t *descriptor_bytes,
                                       uint64_t descriptor_len,
                                       void *owner,
                                       HurrayOwnerReleaseFn owner_release,
                                       struct HurrayTensorContext **out_ctx)
;

#endif  /* HURRAY_H */
