/* Hurray C ABI — https://github.com/pgillet/hurray */

#ifndef HURRAY_H
#define HURRAY_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// The integer version of the Hurray C ABI exposed by this build.
//
// Callers SHOULD retrieve this at runtime via [`hurray_c_abi_version`] and
// compare it to the version they were compiled against.
//
// # Examples
//
// ```
// use hurray_ffi::HURRAY_C_ABI_VERSION;
//
// assert_eq!(HURRAY_C_ABI_VERSION, 2);
// ```
#define HURRAY_C_ABI_VERSION 2

// Opaque handle to a buffer registered with the Hurray C ABI.
//
// This struct is **not** `#[repr(C)]`; its internal layout is an
// implementation detail. Callers MUST treat it as a black-box opaque
// pointer. The handle is heap-allocated by [`hurray_buffer_from_ptr`] and
// MUST be released exactly once by [`hurray_buffer_destroy`].
typedef struct HurrayBuffer HurrayBuffer;

// Opaque handle to a decoded tensor descriptor.
//
// This struct is **not** `#[repr(C)]`; its layout is an implementation
// detail. Callers MUST treat it as a black-box opaque pointer created by
// [`hurray_descriptor_decode`] and destroyed by [`hurray_descriptor_destroy`].
typedef struct HurrayDescriptor HurrayDescriptor;

// Opaque handle to an async streaming reader (full implementation deferred).
//
// A reader bridges `hurray-io`'s async streaming layer into the C ABI.
// The async-to-sync bridging strategy (e.g., blocking executor, channel
// hand-off) is deferred; this stub allows cbindgen to emit the type
// declaration in the generated header.
typedef struct HurrayReader HurrayReader;

// Opaque handle to an async streaming writer (full implementation deferred).
//
// Symmetric to [`HurrayReader`]. Deferred pending the async bridge design.
typedef struct HurrayWriter HurrayWriter;

// Integer status code returned by every Hurray C ABI function.
//
// Zero (`HURRAY_OK`) indicates success. All negative values indicate errors.
// Positive values are reserved for future use.
//
// # Examples
//
// ```
// use hurray_ffi::{HurrayStatus, HURRAY_OK};
//
// fn check(s: HurrayStatus) {
//     assert_eq!(s, HURRAY_OK);
// }
// check(HURRAY_OK);
// ```
typedef int32_t HurrayStatus;

// Optional release callback invoked by [`hurray_buffer_destroy`].
//
// The first argument is the `data` pointer passed to [`hurray_buffer_from_ptr`].
// The second argument is the `release_context` pointer passed to the same
// function. Both arguments carry the exact values provided at construction time.
//
// Implementations MUST NOT call back into the Hurray C ABI from within this
// callback; doing so may cause deadlocks or use-after-free.
typedef void (*HurrayReleaseCallback)(void*, void*);

// Payload for the `ConsumerStream` sync mode handoff.
//
// The consumer supplies this struct when calling
// [`hurray_buffer_handoff_consumer_stream`] to declare the stream on which
// they intend to use the buffer.
typedef struct HurraySyncConsumerStreamPayload {
    // Non-null consumer stream handle (e.g., `cudaStream_t`).
    void *consumer_stream;
    // Wire byte of the device that owns `consumer_stream`.
    uint8_t consumer_stream_device_tag;
} HurraySyncConsumerStreamPayload;

// Optional callback invoked to release a sync event handle.
//
// The first argument is the event handle; the second is the
// `event_release_context` pointer. MUST NOT call back into the Hurray C ABI.
typedef void (*HurrayEventReleaseFn)(void*, void*);

// Payload for the `Event` sync mode handoff.
//
// The consumer supplies this struct when calling
// [`hurray_buffer_handoff_event`] to provide the device event that the
// producer recorded and on which the consumer will wait.
typedef struct HurraySyncEventPayload {
    // Non-null device-event handle (e.g., `cudaEvent_t`).
    void *sync_handle;
    // Wire byte of the device on which `sync_handle` was recorded.
    uint8_t sync_handle_device_tag;
    // Release callback for `sync_handle`; MUST be non-null.
    HurrayEventReleaseFn event_release_fn;
    // Opaque context forwarded to `event_release_fn`; MAY be null.
    void *event_release_context;
} HurraySyncEventPayload;

// Operation completed successfully.
#define HURRAY_OK 0

// The descriptor magic bytes were not `"HRRY"` (`0x48 0x52 0x52 0x59`).
#define HURRAY_ERR_INVALID_MAGIC -1

// The descriptor version is not supported by this implementation.
#define HURRAY_ERR_VERSION_MISMATCH -2

// A layout descriptor field or tag is invalid.
#define HURRAY_ERR_INVALID_LAYOUT -3

// A type tag, device tag, or memory class is invalid.
#define HURRAY_ERR_INVALID_TYPE -4

// An output buffer is too small to hold the result.
#define HURRAY_ERR_BUFFER_TOO_SMALL -5

// A required pointer argument is null.
#define HURRAY_ERR_NULL_POINTER -6

// The function panicked internally; the handle MUST NOT be reused.
#define HURRAY_ERR_INTERNAL_PANIC -7

// The sync mode byte is not a recognized value.
#define HURRAY_ERR_INVALID_SYNC_MODE -8

// A sync-mode handoff payload does not match the buffer's declared sync mode.
#define HURRAY_ERR_SYNC_MODE_MISMATCH -9

// An unclassified internal error occurred.
#define HURRAY_ERR_INTERNAL -10

// Reads the declared alignment of a buffer handle (in bytes).
//
// # Safety
//
// `buffer` and `out_alignment` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_alignment(const struct HurrayBuffer *buffer, uint32_t *out_alignment) ;

// Reads the byte size of a buffer handle.
//
// # Safety
//
// `buffer` and `out_byte_size` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_byte_size(const struct HurrayBuffer *buffer, uint64_t *out_byte_size) ;

// Reads the raw data pointer stored in a buffer handle.
//
// # Safety
//
// `buffer` and `out_data` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_data_ptr(const struct HurrayBuffer *buffer, void **out_data) ;

// Destroys a [`HurrayBuffer`] handle and invokes the release callback.
//
// After this call, `buffer` is no longer valid and MUST NOT be dereferenced.
// In debug builds, a double-free attempt returns [`HURRAY_ERR_INTERNAL`].
//
// # Safety
//
// - `buffer` MUST have been created by [`hurray_buffer_from_ptr`].
// - `buffer` MUST NOT have been previously destroyed.
 HurrayStatus hurray_buffer_destroy(struct HurrayBuffer *buffer) ;

// Reads the device tag wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_device_tag` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_device_tag(const struct HurrayBuffer *buffer, uint8_t *out_device_tag) ;

// Creates a new [`HurrayBuffer`] handle from a raw data pointer and metadata.
//
// The caller retains ownership of `data` until the handle is destroyed via
// [`hurray_buffer_destroy`], at which point the `release` callback (if
// non-null) is invoked with `(data, release_context)`. If `release` is null,
// the caller is responsible for freeing `data` after destroying the handle.
//
// # Arguments
//
// - `data` — Non-null pointer to the first byte of the buffer. MUST be
//   aligned to at least `alignment` bytes.
// - `byte_size` — Length of the buffer in bytes.
// - `alignment` — Declared alignment of `data` in bytes; MUST be a power of
//   two and at least [`hurray_core::MIN_BUFFER_ALIGNMENT`] for non-empty
//   buffers.
// - `device_tag` — Wire byte identifying the memory space (see
//   `docs/spec/buffer-protocol.md § Device Tags`).
// - `sync_mode` — Wire byte for producer/consumer ordering (see
//   `docs/spec/buffer-protocol.md § Synchronization Mode`).
// - `memory_class` — Wire byte for memory accessibility class.
// - `release` — Optional callback invoked on [`hurray_buffer_destroy`].
// - `release_context` — Opaque context pointer forwarded to `release`; MAY
//   be null.
// - `out_handle` — Non-null pointer to a `*mut HurrayBuffer`; set to the
//   newly allocated handle on success.
//
// # Safety
//
// - `data` MUST be a valid, non-null pointer to at least `byte_size` bytes.
// - `data` MUST remain valid until the release callback is called.
// - `out_handle` MUST be a valid, non-null, writable pointer.
// - `release_context` lifetime is caller-managed; it MUST remain valid until
//   the release callback returns.

HurrayStatus hurray_buffer_from_ptr(void *data,
                                    uint64_t byte_size,
                                    uint32_t alignment,
                                    uint8_t device_tag,
                                    uint8_t sync_mode,
                                    uint8_t memory_class,
                                    HurrayReleaseCallback release,
                                    void *release_context,
                                    struct HurrayBuffer **out_handle)
;

// Validates a `ConsumerStream`-mode sync handoff from producer to consumer.
//
// Checks that:
// - The buffer's declared sync mode is [`SyncMode::ConsumerStream`].
// - `payload.consumer_stream` is non-null.
// - `payload.consumer_stream_device_tag` matches the buffer's declared device
//   tag.
//
// Returns [`HURRAY_OK`] if all checks pass; [`HURRAY_ERR_SYNC_MODE_MISMATCH`]
// otherwise.
//
// # Safety
//
// `buffer` and `payload` MUST be valid, non-null pointers pointing to live
// objects.

HurrayStatus hurray_buffer_handoff_consumer_stream(const struct HurrayBuffer *buffer,
                                                   const struct HurraySyncConsumerStreamPayload *payload)
;

// Validates an `Event`-mode sync handoff from producer to consumer.
//
// Checks that:
// - The buffer's declared sync mode is [`SyncMode::Event`].
// - `payload.sync_handle` is non-null.
// - `payload.event_release_fn` is non-null.
// - `payload.sync_handle_device_tag` matches the buffer's declared device tag.
//
// Returns [`HURRAY_OK`] if all checks pass; [`HURRAY_ERR_SYNC_MODE_MISMATCH`]
// otherwise.
//
// # Safety
//
// `buffer` and `payload` MUST be valid, non-null pointers pointing to live
// objects.

HurrayStatus hurray_buffer_handoff_event(const struct HurrayBuffer *buffer,
                                         const struct HurraySyncEventPayload *payload)
;

// Validates a `ProducerSynced`-mode sync handoff.
//
// Checks that the buffer's declared sync mode is
// [`SyncMode::ProducerSynced`]. This mode requires no payload — calling
// this function is itself the assertion that the producer has already issued
// a host-side wait.
//
// Returns [`HURRAY_OK`] if the buffer is `ProducerSynced`;
// [`HURRAY_ERR_SYNC_MODE_MISMATCH`] otherwise.
//
// # Safety
//
// `buffer` MUST be a valid, non-null pointer to a live [`HurrayBuffer`].
 HurrayStatus hurray_buffer_handoff_producer_synced(const struct HurrayBuffer *buffer) ;

// Reads the memory class wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_memory_class` MUST be valid, non-null pointers.

HurrayStatus hurray_buffer_memory_class(const struct HurrayBuffer *buffer,
                                        uint8_t *out_memory_class)
;

// Reads the sync mode wire byte of a buffer handle.
//
// # Safety
//
// `buffer` and `out_sync_mode` MUST be valid, non-null pointers.
 HurrayStatus hurray_buffer_sync_mode(const struct HurrayBuffer *buffer, uint8_t *out_sync_mode) ;

// Returns the [`HURRAY_C_ABI_VERSION`] constant.
//
// This function is infallible and requires no panic barrier.
//
// # Examples
//
// ```
// assert_eq!(unsafe { hurray_ffi::hurray_c_abi_version() }, 2);
// ```
 uint32_t hurray_c_abi_version(void) ;

// Reads the number of buffer handles in the tensor descriptor's buffer table.
//
// # Safety
//
// `handle` and `out_count` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_buffer_count(const struct HurrayDescriptor *handle,
                                            uint32_t *out_count)
;

// Reads the byte offset from the start of buffer 0 to logical element `[0,…,0]`.
//
// # Safety
//
// `handle` and `out_offset` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_byte_offset(const struct HurrayDescriptor *handle,
                                           uint64_t *out_offset)
;

// Decodes a binary tensor descriptor from a byte buffer.
//
// On success, `*out_handle` is set to a newly allocated [`HurrayDescriptor`]
// that MUST be released via [`hurray_descriptor_destroy`].
//
// # Arguments
//
// - `bytes` — Non-null pointer to the first byte of the encoded descriptor.
// - `len` — Number of bytes readable at `bytes`.
// - `out_handle` — Non-null pointer to a `*mut HurrayDescriptor`; set on
//   success.
//
// # Safety
//
// - `bytes` MUST be valid and readable for `len` bytes for the duration of
//   this call.
// - `out_handle` MUST be a valid, non-null, writable pointer.

HurrayStatus hurray_descriptor_decode(const uint8_t *bytes,
                                      uintptr_t len,
                                      struct HurrayDescriptor **out_handle)
;

// Destroys a [`HurrayDescriptor`] handle and frees its memory.
//
// After this call, `handle` is no longer valid and MUST NOT be dereferenced.
//
// # Safety
//
// - `handle` MUST have been created by [`hurray_descriptor_decode`].
// - `handle` MUST NOT have been previously destroyed.
 HurrayStatus hurray_descriptor_destroy(struct HurrayDescriptor *handle) ;

// Reads the element type tag byte of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_tag` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_element_type_tag(const struct HurrayDescriptor *handle,
                                                uint8_t *out_tag)
;

// Reads the layout tag byte of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_tag` MUST be valid, non-null pointers.

HurrayStatus hurray_descriptor_layout_tag(const struct HurrayDescriptor *handle,
                                          uint8_t *out_tag)
;

// Reads the rank (number of dimensions) of the tensor descriptor.
//
// # Safety
//
// `handle` and `out_rank` MUST be valid, non-null pointers.
 HurrayStatus hurray_descriptor_rank(const struct HurrayDescriptor *handle, uint32_t *out_rank) ;

// Reads the shape (dimension sizes) of a tensor descriptor.
//
// This function uses a **capacity/length in-out pattern**:
//
// 1. Set `*out_rank` to the capacity of the `out_dims` array (number of
//    `uint64_t` elements it can hold), or to `0` if `out_dims` is null.
// 2. On return, `*out_rank` always contains the true rank of the tensor.
// 3. If `out_dims` is null OR the capacity was less than the true rank,
//    the function returns [`HURRAY_ERR_BUFFER_TOO_SMALL`] and `*out_rank`
//    contains the true rank so the caller can allocate and retry.
// 4. Otherwise the function writes the dimension sizes into `out_dims[0..rank]`
//    and returns [`HURRAY_OK`].
//
// # Safety
//
// - `handle` and `out_rank` MUST be valid, non-null pointers.
// - If `out_dims` is non-null it MUST be writable for `capacity` × 8 bytes,
//   where `capacity` is the value at `*out_rank` on entry.

HurrayStatus hurray_descriptor_shape(const struct HurrayDescriptor *handle,
                                     uint64_t *out_dims,
                                     uintptr_t *out_rank)
;

#endif  /* HURRAY_H */
